node-eds:
    port: 3000
    log:
        level: debug,
        levels:
            emerg: 0
            error: 3
            warning: 4
            info: 6
            debug: 7
            trace: 8
        colors:
            emerg: red
            error: red
            warning: yellow
            info: white
            debug: green
            trace: blue
        transports: 
            - name: console
              options:
                level: trace
                colorize: true
    repositories:
        repositoryId: DevSHRA
        supportedTypes:
            -symbolicName: HCV_CaseDocuments